become_method: sudo
NODE_PWD: node.pwd
SCRIPTS_MOC_BRANCH: test-init
SCRIPTS_VALIDATOR_BRANCH: master
MAIN_CHAINSPEC_REPO_FETCH: nathPay
GENESIS_BRANCH: test
GENESIS_NETWORK_NAME: test
MOC_ADDRESS: "0x1f23f42c865d7D580C5850fCf13518307C2fa567"
BLK_GAS_LIMIT: "6700000"
NODE_FULLNAME: test-bootnode
NODE_ADMIN_EMAIL: np@iex.ec
username: bootnode
users:
  - name: "{{ username }}"
home: /home/{{ username }}
configure_extended_tcp_settings: false
bootnode_archive: off
bootnode_orchestrator: off
install_debug_tools: yes
reboot_after_completion: false
