- name: Combine Docker daemon environment variable configuration
  set_fact:
    docker_service_envs: "{{ docker_service_envs | combine(_docker_service_opts) | combine(docker_daemon_envs) }}"
  vars:
    _docker_service_opts:
      DOCKER_OPTS: "{{ docker_daemon_opts }}"

- name: Setup Docker environment file {{ docker_envs_dir[_docker_os_dist] }}/docker
  become: true
  template:
    src: docker-envs.j2
    dest: "{{ docker_envs_dir[_docker_os_dist] }}/docker"
  notify: restart docker
  vars:
    docker_envs: "{{ docker_service_envs }}"