---
# https://github.com/moby/moby/issues/35873
# https://access.redhat.com/solutions/2991041
- name: Compatibility check - Fail if both MountFlags=slave and live-restore are set
  fail:
    msg: >
      Setting both `MountFlags=slave` (docker_enable_mount_flag_fix: true)
      and `live-restore=true` (docker_daemon_config['live-restore']: true)
      triggers a bug (https://github.com/moby/moby/issues/35873). For now,
      don't use both.
  when:
    - docker_enable_mount_flag_fix | bool
    - docker_daemon_config['live-restore'] is defined
    - docker_daemon_config['live-restore']


# Issues related to specified URL http://pypi.python.org/simple/ which now must be https.
- name: Compatibility check - Fail if PiP is required due to issues getting it to work smooth in Debian Wheezy
  fail:
    msg: >
      Make sure Docker SDK, docker-compose etc is already in place before using
      this role on a host running Debian Wheezy.
  when:
    - _docker_os_dist == "Debian"
    - _docker_os_dist_major_version == '7'
    - docker_stack | bool or
      docker_sdk | bool or
      docker_pip_upgrade | bool or
      (docker_compose | bool and not docker_compose_no_pip | bool) or
      docker_additional_packages_pip|length > 0