---
- name: Fail if unsupported RedHat version
  fail:
    msg: "RedHat 7 or later is required!"
  when: _docker_os_dist_major_version < '7'

# https://github.com/haxorof/ansible-role-docker-ce/issues/97
- name: Fail if Docker SDK/Stack/Compose shall be installed using PiP on RedHat
  fail:
    msg: "This role does not handle packages coming from PiP!"
  when: (docker_sdk | bool) or (docker_stack | bool)
    or (docker_compose | bool and not docker_compose_no_pip | bool)
