language: python
python: '2.7'
addons:
  apt:
    packages:
    - python-pip
install:
- pip install ansible
- ansible --version
- printf '[defaults]\nroles_path=../' >ansible.cfg
script:
- ansible-playbook tests/ci-test.yml -i tests/hosts --syntax-check
notifications:
  email: false
  webhooks:
    urls:
      - https://galaxy.ansible.com/api/v1/notifications/
      - https://galaxy-qa.ansible.com/api/v1/notifications/
    on_success: always
    on_failure: never
    on_start: never
    on_cancel: never
    on_error: never
  pushover:
    api_key:
      secure: RHH/b7xinF9IV7UWrbzR3cTsvxqCaU2t8Bd2o8XhMOSnire2A8kRZ7kuNzqJR1U1dR4/3a+1oIZGq5CDp2G77UTlS3b26gihMpBe4eX+5cy2kbBBfXDVI95iYQjt70clbclccS4N+PNwwroYedp0baS+LIpXk9v9JyWkDbRtnl3vaJqOdbuhe38bjS2ZoTDzwe5QLpw3kF9j/CAP1bw+FPyCYgqVCzyzp3efeWI4OiehTLEyG3lWz/1q+j5G4AT7BQ6Ylo9n+zSKdBEFSveqYvSUQ0MMet55/4rcoE42HnqXB1/PDMfRBDRfhFOMt7fCE3i46UZjUIYkzxsoHk4N/sap/x4Hb+orx77Sd/9FJNa8pD0xRQHJmOqZU79WOQ4MInf0mrXirY7XpQ5iyU6cFapd21+eY0cuuXaEpeeyDKVVqpQgXNLQMSIUTwA8LNDlDQLSGVyGiXcmDF6S9F3r4AhATjeg1bW3AfvcmOEQzd/XH3OUsIz3sIycpcILPXWKfj83uyq+TywS7DpGz18TEmY0ujjkH2hNV+5FWz9fA/rglQsu6bKESC1h6dG4RvWIwbl/3qL4Hzgc9oGEa3RVC/CWe4CzfdZoh7zsz/Som6HgNqD6Ol8Jyf9tbF0v6Icm1bPlkdd6xiomfg0TU94ndhxoa1j3LXHtolK896JNLl8=
    users:
      secure: nl9MFN/H4ik2IkQV4FT9aRus7tI2YmSDgHQVanpUIlpDsOMQzGuZxHaGG3oWBDdt2yHn/4PakrHr/B3JU2MCxoqBxIj4lL+qoAMY0F4yDdmBK39OhkGNP6c5hRN0qLNx+sq6eSmJCfTyc3l2qhZeqdSILhziwXp2F+tFBOaZKcHUAjF7G3Qx10oLVE6bnIdGSRdE5jWLv/8necPo+m3jc5/N4dHyc6cF/AkZfFBq1qZ0K7YBhe2omQ5NDLlOz+YPHPM9uxiESnOr144lhnjjrDpl0x3PXEJut8reFugdgZj/J5tjCWgzCLmNfOJn+gcgaTzn4Q4EGUB2B4HxUABhhJoCe6kIjYQeicWBLeYYg4s6m2ftZglpAOpDLezPsV8K52ZBKqFFxR3f04O/DggmBFYTQAPa+a1YCDrYMGU4PWWtkdGFF/kDgiIgx3+tKDCF4cNhjNVy/tfHqXavzOhDnOesgQ8mhz/QPPSigGd4xJgRFEGLPsdxTMQY9erFGKWURPw6y64o/Xdlxqobxsr/rt30c/4UVKtj5kSRN9OhIhdJcIoZwuu+1m6mCkkpjiljhzQSkZ0cHGKVT2Y1QGRMtq4Bm0iPib/saLgmlWwNaNjHN8I9U+ErYSEPwird0JeIoCLsld/HsuBrNMFEEvu0bzPEm6C6zp3zHDYyixSG1yI=
