FROM node:11-alpine

RUN apk add --no-cache git python make g++

ENV NODE_NO_WARNINGS 1
ENV user node
ENV PATH=/home/node/.npm-global/bin:$PATH
ENV NPM_CONFIG_PREFIX=/home/node/.npm-global

RUN mkdir /home/$user/app
COPY . /home/$user/app/
RUN chown -R $user: /home/$user/app

USER $user

RUN mkdir /home/$user/.npm-global

WORKDIR /home/$user/app
RUN npm i
RUN npm run build
RUN npm i -g serve

ENTRYPOINT ["serve", "-s", "build", "-l", "3000"]
