---
- name: preconf.chrony - check if NTP is installed
  become: yes
  become_user: root
  command: "systemctl is-active ntpd"
  register: ntp_active
  failed_when: ntp_active.rc not in [0,3]

- name: chrony
  become: yes
  become_user: root
  when: ntp_active.stdout == "inactive"
  block:
    - name: preconf.chrony - install package
      yum:
        name: chrony

    - name: preconf.chrony - remove default servers
      lineinfile:
        dest: /etc/chrony.conf
        regexp : '^server.*'
        state: absent
    - name: preconf.chrony - select amazon time server (for AWS)
      lineinfile:
        dest: /etc/chrony.conf
        insertafter: '# Please consider'
        line: 'server 169.254.169.123 prefer iburst'
        state: present
      notify:
        - restart chrony centos
      when: ansible_bios_version is search("amazon")

    - name: preconf.chrony - ensure chrony is running and enabled to start at boot
      service:
        name: chronyd
        state: started
        enabled: yes
