---

- import_tasks: ssh.yml
- import_tasks: packages.yml
- import_tasks: vars.yml
- import_tasks: chrony.yml
- import_tasks: logrotate.yml
- import_tasks: swap.yml
- import_tasks: logs.yml
- import_tasks: keys.yml
- import_tasks: ports.yml
  when: "'netstat' not in ansible_hostname"
- import_tasks: spec.yml
  when: "'netstat' not in ansible_hostname"
