---
- name: Install packages
  apt: name={{ item }} state=present update_cache=yes
  with_items:
    - haveged
    - openssh-client
    - sudo
    - git
    - build-essential
    - python3-pip
    - python-pip
