---
- name: Fix ssh Ciphers
  blockinfile:
    path: /etc/ssh/sshd_config
    insertafter: '^ServerKeyBits'
    content: |
      Ciphers chacha20-poly1305@openssh.com,aes256-gcm@openssh.com,aes128-gcm@openssh.com,aes256-ctr,aes192-ctr,aes128-ctr
      MACs hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,umac-128-etm@openssh.com
  notify:
    - restart sshd

- name: Ensure sshd is running and enabled to start at boot
  service: name=sshd state=started enabled=yes
