---
- name: Check if swap file exists (Centos)
  stat:
    path: /swapfile
  register: swap_file_check

- name: create file for swap (Centos)
  shell: dd if=/dev/zero of=/swapfile count=1024 bs=1MiB
  when: not swap_file_check.stat.exists
  tags:
    - skip_ansible_lint

- name: format swap file (Centos)
  shell: /sbin/mkswap /swapfile
  when: not swap_file_check.stat.exists
  tags:
    - skip_ansible_lint

- name: set permission to swap file (Centos)
  file: path=/swapfile owner=root group=root mode=0600

- name: add swap file to system (Centos)
  become: true
  shell: /sbin/swapon /swapfile
  when: not swap_file_check.stat.exists
  tags:
    - skip_ansible_lint

- name: write changes to fstab (Centos)
  mount: name=none src=/swapfile fstype=swap opts=sw passno=0 dump=0 state=present
