---
- name: Set vm.swappiness system parameter
  sysctl: name=vm.swappiness value=10 state=present

- name: Set vm.vfs_cache_pressure system parameter
  sysctl: name=vm.vfs_cache_pressure value=50 state=present

- name: Set net.core.somaxconn system parameter
  sysctl: name=net.core.somaxconn value=1000 state=present

- name: Set nofile soft limit
  lineinfile: dest=/etc/security/limits.conf line="* soft nofile 100000" state=present

- name: Set nofile hard limit
  lineinfile: dest=/etc/security/limits.conf line="* hard nofile 100000" state=present
