dependencies:
  - { role: usermanager }
  - { role: preconf }
  - { role: nodejs }
  - { role: poa-logrotate }
  - { role: nginx-letsencrypt }
  - { role: debug-tools, when: "install_debug_tools == 'yes'" }
