---
- name: Clone token bridge repo from GitHub
  git:
    repo: "https://github.com/{{ MAIN_REPO_FETCH }}/tokenbridge"
    dest: "/home/ubuntu/tokenbridge"
    version: "{{ tokenbridge_version }}"
    force: yes

- name: Copy environment file for tokenbridge oracle
  template: src=environment.j2 dest=/home/ubuntu/tokenbridge/oracle/.env owner=ubuntu group=ubuntu mode=0644

- name: Building and starting tokenbridge oracle (can take > 10 min)
  shell: "docker-compose -f /home/ubuntu/tokenbridge/oracle/docker-compose.yml --project-directory /home/ubuntu/tokenbridge/oracle/ up -d --build"

- name: Setup ufw firewall
  import_tasks: ufw.yml
  when: install_firewall

- name: restart machine after setup
  shell: shutdown -r 1
  when: reboot_after_completion == true
