---                                                                                                                                     
- import_tasks: debug-tools-ubuntu.yml                                                                                                 
  when: ansible_os_family == "Debian"                                                                                                   
                                                                                                                                        
- import_tasks: debug-tools-centos.yml                                                                                                  
  when: ansible_os_family == "RedHat"     
