---
- name: Set distribution facts
  set_fact:
    _docker_os_dist: "{{ ansible_distribution }}"
    _docker_os_dist_release: "{{ ansible_distribution_release }}"
    _docker_os_dist_major_version: "{{ ansible_distribution_major_version }}"
    _docker_os_dist_check: yes
  tags: ["always"]

- name: Reinterpret distribution facts for Linux Mint 18
  set_fact:
    _docker_os_dist: "Ubuntu"
    _docker_os_dist_release: "xenial"
    _docker_os_dist_major_version: "16"
  when:
    _docker_os_dist == "Linux Mint" and
    _docker_os_dist_major_version == "18"
  tags: ["always"]

- name: Reset role variables
  set_fact:
    docker_systemd_service_config_tweaks: []
    docker_service_envs: {}
  tags: ["always"]

- name: Temporary handling of deprecated variable docker_enable_ce_edge (#54)
  set_fact:
    docker_channel: edge
  when:
    - docker_enable_ce_edge is defined
    - docker_enable_ce_edge
  tags: ["always"]

- name: Temporary handling of deprecated variable docker_pkg_name
  set_fact:
    docker_version: "{{ docker_pkg_name | regex_replace('^docker-ce.(.+)$', '\\1') }}"
  when: docker_pkg_name is match('docker-ce' + docker_os_pkg_version_separator[_docker_os_dist])
  tags: ["always"]

- name: Compatibility and distribution checks
  include_tasks: checks.yml
  when: docker_do_checks | bool
  tags: ["always"]

- name: Install and configure Docker CE
  block:
    - name: Network access disabled
      debug:
        msg: "Tasks requiring network access will be skipped!"
      when: not docker_network_access | bool

    - name: Remove Docker versions before Docker CE
      include_tasks: remove-pre-docker-ce.yml
      when:
        - docker_remove_pre_ce | bool
        - docker_network_access | bool
      tags: ["install"]

    - name: Setup Docker package repositories
      include_tasks: setup-repository.yml
      tags: ["install"]

    - name: Install Docker
      include_tasks: install-docker.yml
      when: docker_network_access | bool
      tags: ["install"]

    - name: Configure audit logging
      include_tasks: setup-audit.yml
      tags: ["configure"]

    - name: Apply workarounds for bugs and/or tweaks
      include_tasks: bug-tweaks.yml
      tags: ["configure"]

    - name: Configure Docker
      include_tasks: configure-docker.yml
      tags: ["configure"]

    - name: Postinstall tasks
      include_tasks: postinstall.yml
      when: docker_network_access | bool
      tags: ["install", "postinstall"]
  when: not docker_remove | bool

- name: Remove Docker CE and related configuration
  include_tasks: remove-docker.yml
  when: docker_remove | bool
