# Best effort to remove Docker CE and related configuration

- name: Stop Docker service
  become: yes
  service:
    name: docker
    state: stopped
  ignore_errors: yes

- name: Ensure Docker CE is removed (CentOS/Fedora/RedHat)
  become: yes
  package:
    name: "{{ item }}"
    state: absent
  with_items: "{{ docker_packages }}"
  register: _pkg_result
  until: _pkg_result is succeeded
  when: _docker_os_dist != "Ubuntu" and
        _docker_os_dist != "Debian"

- name: Ensure Docker CE is removed (Ubuntu/Debian)
  become: yes
  apt:
    name: "{{ item }}"
    state: absent
    purge: yes
  with_items: "{{ docker_packages }}"
  register: _pkg_result
  until: _pkg_result is succeeded
  when: _docker_os_dist == "Ubuntu" or
        _docker_os_dist == "Debian"

- name: Remove network interface docker0
  become: yes
  command: ip link del docker0
  args:
    warn: no
  ignore_errors: yes
  changed_when: no
  tags:
    - skip_ansible_lint

- name: Remove dockerd from alternatives configuration
  become: yes
  shell: alternatives --remove dockerd /usr/bin/dockerd-ce
  ignore_errors: yes
  changed_when: no
  tags:
    - skip_ansible_lint

- name: Clean yum cache (CentOS/RedHat)
  become: yes
  command: yum clean all --enablerepo=\*
  args:
    warn: no
  changed_when: no
  when: _docker_os_dist == "CentOS" or
        _docker_os_dist == "RedHat"

- name: Clean dnf cache
  become: yes
  command: dnf clean all --enablerepo=\*
  args:
    warn: no
  changed_when: no
  when: _docker_os_dist == "Fedora"

- name: Clean apt cache
  become: yes
  command: apt-get clean
  changed_when: no
  when: _docker_os_dist == "Ubuntu" or
        _docker_os_dist == "Debian"
  tags:
    - skip_ansible_lint

- name: Remove repository docker specific repo file
  become: yes
  yum_repository:
    name: docker-ce
    file: docker-ce
    state: absent
  when: _docker_os_dist != "Ubuntu" and
        _docker_os_dist != "Debian"

- name: Ensure Docker CE and configuration files are removed
  become: yes
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    # all distributions
    - "{{ docker_envs_dir[_docker_os_dist] }}/docker"
    - "{{ docker_envs_dir[_docker_os_dist] }}/docker-envs"
    - /etc/audit/rules.d/docker.rules
    # centos
    - /etc/yum.repos.d/docker-ce.repo
    - /etc/systemd/system/docker.service.d
    - /etc/docker
    - /usr/bin/dockerd
    - /run/docker
    # ubuntu/debian
    - /etc/apt/sources.list.d/docker-ce.list

- name: Ensure additional files and data directories are removed
  become: yes
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - /var/lib/docker
    - /var/lib/docker-engine
    - "{{ docker_remove_additional }}"
  when: docker_remove_all | bool

- name: Find Docker related diretories in package cache
  become: yes
  find:
    paths: "{{ _os_pkg_cache_dirs[_docker_os_dist] }}"
    file_type: directory
    recurse: yes
    patterns: "docker-ce*"
  vars:
    _os_pkg_cache_dirs:
      RedHat: /var/cache/yum
      CentOS: /var/cache/yum
      Fedora: /var/cache/dnf
  register: _remove_cache_dirs
  when: _docker_os_dist == "Fedora" or
        _docker_os_dist == "CentOS" or
        _docker_os_dist == "RedHat"

- name: Remove dangeling files/directories in package cache
  become: yes
  file:
    path: "{{ item.path }}"
    state: absent
  with_items: "{{ _remove_cache_dirs.files }}"
  when: _docker_os_dist == "Fedora" or
        _docker_os_dist == "CentOS" or
        _docker_os_dist == "RedHat"
