---
- name: Reset fact related to removal of old Docker
  set_fact:
    _remove_old_docker: false

- name: Determine Docker version
  shell: "docker version --format='{{ '{{' }} .Client.Version {{ '}}' }}' 2>/dev/null"
  register: _cmd_docker_version
  changed_when: false
  failed_when: false
  check_mode: no

- name: Set fact if old Docker installation shall be removed
  set_fact:
    _remove_old_docker: true
  when:
    - _cmd_docker_version.stdout_lines is defined
    - _cmd_docker_version.stdout_lines[0] is defined
    - _cmd_docker_version.stdout_lines[0] is version('17', '<')

- name: Check if Docker is running
  become: true
  systemd:
    name: docker
  ignore_errors: yes
  register: _service_docker_status
  check_mode: no
  when: _remove_old_docker | bool

- name: Stop Docker service
  service:
    name: docker
    state: stopped
  when: "_service_docker_status.rc | default(1) == 0"

- name: Remove old Docker installation before Docker CE
  become: true
  package:
    name: "{{ item }}"
    state: absent
  register: _pkg_result
  until: _pkg_result is succeeded
  when: _remove_old_docker | bool
  with_items:
    - "{{ docker_old_packages[_docker_os_dist] }}"
