---
- name: Get public IP
  ipify_facts:
  register: public_ip

- name: Create node.toml
  template: src=node.toml.j2 dest={{ home }}/node.toml owner={{ username }} group={{ username }} mode=0644

- name: change permission
  file:
    path: "/home/{{ username }}"
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: 0744
    recurse: yes

- pause: seconds=3

- name: Poa parity restarted
  service: name=poa-parity state=restarted

- name: restart machine after setup
  shell: shutdown -r 1
  when: reboot_after_completion == true

#- file: path={{ home }} owner={{ username }} group={{ username }} recurse=yes
