---
- name: Get public IP
  ipify_facts:
  register: public_ip

- name: Copy bootnode.txt
  copy: src=./getBootnode.sh dest={{ home }}/getBootnode.sh owner={{ username }} group={{ username }} mode=0777

- name: Getting bootnode.txt
  shell: "{{ home }}/getBootnode.sh"

- name: Create node.toml
  template: src=node.toml.j2 dest={{ home }}/node.toml owner={{ username }} group={{ username }} mode=0644

- name: change permission
  file:
    path: /home/{username}/*
    onwer: {username}
    group: {username}
    mode: 0775
    recurse: yes

- name: Poa parity restarted
  service: name=poa-parity state=restarted

- name: restart machine after setup
  shell: shutdown -r 1
  when: reboot_after_completion == true

#- file: path={{ home }} owner={{ username }} group={{ username }} recurse=yes
