galaxy_info:
  role_name: docker_ce
  author: Bjorn Oscarsson
  company: none
  description: "Installs and configures Docker Community Edition (CE)"
  min_ansible_version: 2.6
  license: MIT
  platforms:
  - name: Fedora
    versions:
      - 25
      - 26
      - 27
      - 28
      - 29

  - name: EL
    versions:
      - 7

  - name: Debian
    versions:
      - wheezy
      - jessie
      - stretch
      - buster

  - name: Ubuntu
    versions:
      - trusty
      - artful
      - xenial
      - bionic
      - cosmic

  galaxy_tags:
    - docker
    - containers
    - virtualization
    - compose
    - orchestration
    - system

dependencies: []
